# Generated by Django 5.2.4 on 2025-08-02 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NepseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock symbol (e.g., MHL, NABIL)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full company name', max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('last_traded_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='TMSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100)),
                ('tms_server', models.IntegerField(default=52)),
                ('server_description', models.CharField(blank=True, help_text='Description of this TMS server', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_ver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('tms_server_number', models.IntegerField(default=52, help_text='TMS server number (51, 52, 53, 54)')),
                ('tms_configured', models.BooleanField(default=False, help_text='Whether user has configured TMS access')),
                ('last_tms_sync', models.DateTimeField(blank=True, help_text='Last successful TMS data sync', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Share_Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrip', models.CharField(max_length=20)),
                ('units', models.PositiveIntegerField()),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('remaining_units', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Share_Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_sold', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('transaction_group', models.CharField(blank=True, help_text='Groups sell records from the same user transaction', max_length=100, null=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.share_buy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
